pipeline{
    agent any
    stages{
        stage("Run the Program"){
            steps{
                sh """
                    sleep ${params.SLEEP_TIME}
                    echo 'Hello, ${params.NAME}!'
                """
            }
        }
    }
}