pipeline {
    agent any

    tools {
        nodejs "23.5.0"
    }

    environment {
        PROJECT_DIR = "SOLAR-SYSTEM-GITEA"
    }

    stages {
        stage("Installing Dependencies") {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "npm i --no-audit"
                }
            }
        }

        stage("Dependency Scanning") {
            parallel {
                stage("NPM Dependency Audit") {
                    steps {
                        dir("${PROJECT_DIR}") {
                            sh "npm audit --audit-level=critical"
                        }
                    }
                }

                stage("OWASP Dependency Check") {
                    steps {
                        dir("${PROJECT_DIR}") {
                            dependencyCheck additionalArguments: '''
                                --scan \'./\'
                                --out \'./\'
                                --format \'ALL\'
                                --prettyPrint''', odcInstallation: 'OWASP-DepCheck-12'
                        }
                    }
                }
            }
        }
    }
}