pipeline{
    agent any
    stages{
        stage("Installing Dependencies"){
            steps{
                sh 'npm install'
            }
        }
        stage("Build"){
            steps{
                sh 'nohup node app.js > app.log 2>&1 &'
                sh 'sleep 10'
            }
        }
    }
}